/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 24 16:38:15 GMT 2020
 */

package org.apache.commons.math.analysis.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math.analysis.function.Gaussian;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

public class Gaussian$Parametric_ESTest_EvoSuite extends Gaussian$Parametric_ESTest_scaffolding_EvoSuite {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = 1341.41453;
      doubleArray0[1] = 1024.0;
      doubleArray0[2] = 1341.41453;
      double[] doubleArray1 = gaussian_Parametric0.gradient(1341.41453, doubleArray0);
      assertArrayEquals(new double[] {0.9723921552303553, 0.2300939732091096, 0.05444638381992337}, doubleArray1, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[0] = 1341.41453;
      doubleArray0[2] = 1341.41453;
      double[] doubleArray1 = gaussian_Parametric0.gradient(1341.41453, doubleArray0);
      assertArrayEquals(new double[] {0.6065306597126334, 0.6065306597126334, 0.6065306597126334}, doubleArray1, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[2] = 4.0;
      double[] doubleArray1 = gaussian_Parametric0.gradient(0.0, doubleArray0);
      assertArrayEquals(new double[] {1.0, 0.0, 0.0}, doubleArray1, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[1] = 1024.0;
      doubleArray0[2] = 1341.41453;
      double[] doubleArray1 = gaussian_Parametric0.gradient(1341.41453, doubleArray0);
      assertArrayEquals(new double[] {0.9723921552303553, 0.0, 0.0}, doubleArray1, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[1] = 1024.0;
      doubleArray0[2] = 1341.41453;
      double double0 = gaussian_Parametric0.value(1341.41453, doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Gaussian.Parametric gaussian_Parametric0 = new Gaussian.Parametric();
      double[] doubleArray0 = new double[3];
      doubleArray0[2] = 1341.41453;
      double double0 = gaussian_Parametric0.value(1341.41453, doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

}
