/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 24 16:50:55 GMT 2020
 */

package org.joda.time;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.Chronology;
import org.joda.time.Days;
import org.joda.time.DurationFieldType;
import org.joda.time.Hours;
import org.joda.time.LocalTime;
import org.joda.time.Minutes;
import org.joda.time.Months;
import org.joda.time.MutablePeriod;
import org.joda.time.Period;
import org.joda.time.PeriodType;
import org.joda.time.ReadablePeriod;
import org.joda.time.Seconds;
import org.joda.time.chrono.IslamicChronology;
import org.joda.time.chrono.JulianChronology;

public class PeriodType_ESTest_EvoSuite extends PeriodType_ESTest_scaffolding_EvoSuite {

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearMonthDayTime();
      assertEquals(7, periodType0.size());
      assertEquals("YearMonthDayTime", periodType0.getName());
      assertNotNull(periodType0);
      
      Minutes minutes0 = Minutes.THREE;
      assertEquals(3, minutes0.getMinutes());
      assertEquals(1, minutes0.size());
      assertNotNull(minutes0);
      
      int[] intArray0 = new int[1];
      boolean boolean0 = periodType0.addIndexedField(minutes0, 0, intArray0, (-194));
      assertEquals(1, intArray0.length);
      assertArrayEquals(new int[] {(-194)}, intArray0);
      assertTrue(boolean0);
      assertEquals(7, periodType0.size());
      assertEquals("YearMonthDayTime", periodType0.getName());
      assertEquals(3, minutes0.getMinutes());
      assertEquals(1, minutes0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearWeekDayTime();
      assertEquals("YearWeekDayTime", periodType0.getName());
      assertEquals(7, periodType0.size());
      assertNotNull(periodType0);
      
      DurationFieldType durationFieldType0 = DurationFieldType.WEEKS_TYPE;
      assertEquals("weeks", durationFieldType0.toString());
      assertEquals("weeks", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      boolean boolean0 = periodType0.isSupported(durationFieldType0);
      assertTrue(boolean0);
      assertEquals("YearWeekDayTime", periodType0.getName());
      assertEquals(7, periodType0.size());
      assertEquals("weeks", durationFieldType0.toString());
      assertEquals("weeks", durationFieldType0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PeriodType periodType0 = PeriodType.seconds();
      assertEquals(1, periodType0.size());
      assertEquals("Seconds", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withSecondsRemoved();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(1, periodType0.size());
      assertEquals("Seconds", periodType0.getName());
      assertEquals("SecondsNoSeconds", periodType1.getName());
      assertEquals(0, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PeriodType periodType0 = PeriodType.days();
      assertEquals(1, periodType0.size());
      assertEquals("Days", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withSecondsRemoved();
      assertEquals(1, periodType0.size());
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType1.size());
      assertEquals("Days", periodType1.getName());
      assertNotNull(periodType1);
      assertSame(periodType0, periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PeriodType periodType0 = PeriodType.months();
      assertEquals("Months", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withMonthsRemoved();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Months", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals("MonthsNoMonths", periodType1.getName());
      assertEquals(0, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PeriodType periodType0 = PeriodType.minutes();
      assertEquals(1, periodType0.size());
      assertEquals("Minutes", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withMinutesRemoved();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(1, periodType0.size());
      assertEquals("Minutes", periodType0.getName());
      assertEquals("MinutesNoMinutes", periodType1.getName());
      assertEquals(0, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertEquals("days", durationFieldType0.getName());
      assertEquals("days", durationFieldType0.toString());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withMillisRemoved();
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals(1, periodType1.size());
      assertEquals("Days", periodType1.getName());
      assertNotNull(periodType1);
      assertSame(periodType0, periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PeriodType periodType0 = PeriodType.days();
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withDaysRemoved();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals(0, periodType1.size());
      assertEquals("DaysNoDays", periodType1.getName());
      assertNotNull(periodType1);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
      
      PeriodType periodType2 = periodType1.withWeeksRemoved();
      assertFalse(periodType0.equals((Object)periodType1));
      assertFalse(periodType1.equals((Object)periodType0));
      assertFalse(periodType2.equals((Object)periodType0));
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals(0, periodType1.size());
      assertEquals("DaysNoDays", periodType1.getName());
      assertEquals("DaysNoDays", periodType2.getName());
      assertEquals(0, periodType2.size());
      assertNotNull(periodType2);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType0, periodType2);
      assertNotSame(periodType1, periodType0);
      assertSame(periodType1, periodType2);
      assertNotSame(periodType2, periodType0);
      assertSame(periodType2, periodType1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PeriodType periodType0 = PeriodType.years();
      assertEquals("Years", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withYearsRemoved();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Years", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals("YearsNoYears", periodType1.getName());
      assertEquals(0, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
      
      int int0 = periodType1.size();
      assertFalse(periodType0.equals((Object)periodType1));
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(0, int0);
      assertEquals("Years", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals("YearsNoYears", periodType1.getName());
      assertEquals(0, periodType1.size());
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearMonthDayTime();
      assertEquals(7, periodType0.size());
      assertEquals("YearMonthDayTime", periodType0.getName());
      assertNotNull(periodType0);
      
      DurationFieldType durationFieldType0 = DurationFieldType.months();
      assertEquals("months", durationFieldType0.getName());
      assertEquals("months", durationFieldType0.toString());
      assertNotNull(durationFieldType0);
      
      int int0 = periodType0.indexOf(durationFieldType0);
      assertEquals(1, int0);
      assertEquals(7, periodType0.size());
      assertEquals("YearMonthDayTime", periodType0.getName());
      assertEquals("months", durationFieldType0.getName());
      assertEquals("months", durationFieldType0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[3];
      int[] intArray0 = new int[5];
      PeriodType periodType0 = new PeriodType("", durationFieldTypeArray0, intArray0);
      assertEquals(3, durationFieldTypeArray0.length);
      assertEquals(5, intArray0.length);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0}, intArray0);
      assertEquals("", periodType0.getName());
      assertEquals(3, periodType0.size());
      assertNotNull(periodType0);
      
      String string0 = periodType0.getName();
      assertEquals(3, durationFieldTypeArray0.length);
      assertEquals(5, intArray0.length);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0}, intArray0);
      assertEquals("", string0);
      assertEquals("", periodType0.getName());
      assertEquals(3, periodType0.size());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearWeekDay();
      assertEquals("YearWeekDay", periodType0.getName());
      assertEquals(3, periodType0.size());
      assertNotNull(periodType0);
      
      Months months0 = Months.TWELVE;
      assertEquals(12, months0.getMonths());
      assertEquals(1, months0.size());
      assertNotNull(months0);
      
      int int0 = periodType0.getIndexedField(months0, 0);
      assertEquals(12, int0);
      assertEquals("YearWeekDay", periodType0.getName());
      assertEquals(3, periodType0.size());
      assertEquals(12, months0.getMonths());
      assertEquals(1, months0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Months months0 = Months.THREE;
      assertEquals(3, months0.getMonths());
      assertEquals(1, months0.size());
      assertNotNull(months0);
      
      PeriodType periodType0 = months0.getPeriodType();
      assertEquals(3, months0.getMonths());
      assertEquals(1, months0.size());
      assertEquals(1, periodType0.size());
      assertEquals("Months", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.millis();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(1, periodType1.size());
      assertEquals("Millis", periodType1.getName());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
      
      boolean boolean0 = periodType1.equals(periodType0);
      assertFalse(periodType0.equals((Object)periodType1));
      assertFalse(periodType1.equals((Object)periodType0));
      assertFalse(boolean0);
      assertEquals(3, months0.getMonths());
      assertEquals(1, months0.size());
      assertEquals(1, periodType0.size());
      assertEquals("Months", periodType0.getName());
      assertEquals(1, periodType1.size());
      assertEquals("Millis", periodType1.getName());
      assertNotSame(periodType0, periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearDay();
      assertEquals("YearDay", periodType0.getName());
      assertEquals(2, periodType0.size());
      assertNotNull(periodType0);
      
      boolean boolean0 = periodType0.equals(periodType0);
      assertTrue(boolean0);
      assertEquals("YearDay", periodType0.getName());
      assertEquals(2, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PeriodType periodType0 = PeriodType.days();
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      DurationFieldType durationFieldType0 = DurationFieldType.WEEKS_TYPE;
      assertEquals("weeks", durationFieldType0.toString());
      assertEquals("weeks", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      int int0 = periodType0.indexOf(durationFieldType0);
      assertEquals((-1), int0);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertEquals("weeks", durationFieldType0.toString());
      assertEquals("weeks", durationFieldType0.getName());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(4, days0.getDays());
      assertEquals(1, days0.size());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(4, days0.getDays());
      assertEquals(1, days0.size());
      assertEquals("days", durationFieldType0.getName());
      assertEquals("days", durationFieldType0.toString());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.millis();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Millis", periodType1.getName());
      assertEquals(1, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PeriodType periodType0 = PeriodType.seconds();
      assertEquals(1, periodType0.size());
      assertEquals("Seconds", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.seconds();
      assertEquals(1, periodType1.size());
      assertEquals("Seconds", periodType1.getName());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(4, days0.getDays());
      assertEquals(1, days0.size());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(4, days0.getDays());
      assertEquals(1, days0.size());
      assertEquals("days", durationFieldType0.toString());
      assertEquals("days", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.minutes();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Minutes", periodType1.getName());
      assertEquals(1, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertEquals("days", durationFieldType0.toString());
      assertEquals("days", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals(1, periodType0.size());
      assertEquals("Days", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.hours();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(1, periodType1.size());
      assertEquals("Hours", periodType1.getName());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PeriodType periodType0 = PeriodType.hours();
      assertEquals("Hours", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      periodType0.hashCode();
      assertEquals("Hours", periodType0.getName());
      assertEquals(1, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PeriodType periodType0 = PeriodType.days();
      assertEquals(1, periodType0.size());
      assertEquals("Days", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.days();
      assertEquals(1, periodType1.size());
      assertEquals("Days", periodType1.getName());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PeriodType periodType0 = PeriodType.weeks();
      assertEquals(1, periodType0.size());
      assertEquals("Weeks", periodType0.getName());
      assertNotNull(periodType0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      PeriodType periodType0 = PeriodType.months();
      assertEquals("Months", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.months();
      assertEquals("Months", periodType1.getName());
      assertEquals(1, periodType1.size());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      PeriodType periodType0 = PeriodType.years();
      assertEquals(1, periodType0.size());
      assertEquals("Years", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.years();
      assertEquals("Years", periodType1.getName());
      assertEquals(1, periodType1.size());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertEquals("days", durationFieldType0.toString());
      assertEquals("days", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals("Days", periodType0.getName());
      assertEquals(1, periodType0.size());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.time();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals("Time", periodType1.getName());
      assertEquals(4, periodType1.size());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertNotNull(days0);
      
      DurationFieldType durationFieldType0 = days0.getFieldType();
      assertEquals(1, days0.size());
      assertEquals(4, days0.getDays());
      assertEquals("days", durationFieldType0.toString());
      assertEquals("days", durationFieldType0.getName());
      assertNotNull(durationFieldType0);
      
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals(1, durationFieldTypeArray0.length);
      assertEquals(1, periodType0.size());
      assertEquals("Days", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.dayTime();
      assertFalse(periodType1.equals((Object)periodType0));
      assertEquals(5, periodType1.size());
      assertEquals("DayTime", periodType1.getName());
      assertNotNull(periodType1);
      assertNotSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearDay();
      assertEquals(2, periodType0.size());
      assertEquals("YearDay", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.yearDay();
      assertEquals(2, periodType1.size());
      assertEquals("YearDay", periodType1.getName());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearDayTime();
      assertEquals(6, periodType0.size());
      assertEquals("YearDayTime", periodType0.getName());
      assertNotNull(periodType0);
      
      PeriodType periodType1 = PeriodType.yearDayTime();
      assertEquals("YearDayTime", periodType1.getName());
      assertEquals(6, periodType1.size());
      assertNotNull(periodType1);
      assertSame(periodType1, periodType0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType1 = PeriodType.yearWeekDay();
      assertFalse(periodType1.equals((Object)periodType0));
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PeriodType.yearWeekDayTime();
      PeriodType periodType0 = PeriodType.yearWeekDayTime();
      assertEquals(7, periodType0.size());
      assertEquals("YearWeekDayTime", periodType0.getName());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearMonthDay();
      assertNotNull(periodType0);
      
      DurationFieldType durationFieldType0 = periodType0.getFieldType(0);
      assertNotNull(durationFieldType0);
      
      int int0 = periodType0.indexOf(durationFieldType0);
      assertEquals("YearMonthDay", periodType0.getName());
      assertEquals(0, int0);
      assertEquals("years", durationFieldType0.toString());
      assertEquals(3, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType0 = PeriodType.yearMonthDay();
      assertEquals(3, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType0 = PeriodType.yearMonthDayTime();
      assertEquals(7, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType1 = PeriodType.standard();
      assertFalse(periodType1.equals((Object)periodType0));
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType1 = periodType0.withWeeksRemoved();
      assertEquals("Days", periodType1.getName());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PeriodType periodType0 = PeriodType.standard();
      PeriodType periodType1 = periodType0.withHoursRemoved();
      assertEquals(7, periodType1.size());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      PeriodType periodType0 = PeriodType.standard();
      int int0 = periodType0.size();
      assertEquals(8, int0);
      assertEquals("Standard", periodType0.getName());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      PeriodType periodType0 = PeriodType.standard();
      String string0 = periodType0.getName();
      assertEquals("Standard", string0);
      assertEquals(8, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      PeriodType periodType0 = PeriodType.years();
      assertNotNull(periodType0);
      
      PeriodType periodType1 = periodType0.withDaysRemoved();
      assertEquals("Years", periodType1.getName());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType1 = periodType0.withYearsRemoved();
      assertEquals(1, periodType1.size());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Months months0 = Months.THREE;
      PeriodType periodType0 = months0.getPeriodType();
      assertNotNull(periodType0);
      
      boolean boolean0 = periodType0.equals(PeriodType.SECOND_INDEX);
      assertEquals("Months", periodType0.getName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearMonthDayTime();
      PeriodType periodType1 = periodType0.withMonthsRemoved();
      assertEquals(6, periodType1.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      PeriodType periodType0 = PeriodType.yearWeekDay();
      assertNotNull(periodType0);
      
      Months months0 = Months.TWELVE;
      int[] intArray0 = new int[2];
      boolean boolean0 = periodType0.addIndexedField(months0, 0, intArray0, 0);
      assertEquals("YearWeekDay", periodType0.getName());
      assertEquals(3, periodType0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Months months0 = Months.THREE;
      MutablePeriod mutablePeriod0 = months0.toMutablePeriod();
      PeriodType periodType0 = PeriodType.yearWeekDayTime();
      assertNotNull(periodType0);
      
      int[] intArray0 = new int[3];
      periodType0.setIndexedField(mutablePeriod0, 0, intArray0, 5);
      assertEquals(7, periodType0.size());
      assertArrayEquals(new int[] {5, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Seconds seconds0 = Seconds.seconds(3);
      PeriodType periodType0 = seconds0.getPeriodType();
      int int0 = periodType0.getIndexedField(seconds0, 3);
      assertEquals(0, int0);
      assertEquals("Seconds", periodType0.getName());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      boolean boolean0 = periodType0.isSupported(durationFieldType0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      PeriodType periodType0 = PeriodType.time();
      DurationFieldType durationFieldType0 = DurationFieldType.days();
      boolean boolean0 = periodType0.isSupported(durationFieldType0);
      assertFalse(boolean0);
      assertEquals(4, periodType0.size());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      IslamicChronology islamicChronology0 = IslamicChronology.getInstanceUTC();
      LocalTime localTime0 = new LocalTime((Chronology) islamicChronology0);
      Period period0 = Period.fieldDifference(localTime0, localTime0);
      assertNotNull(period0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[2];
      DurationFieldType durationFieldType0 = DurationFieldType.days();
      durationFieldTypeArray0[0] = durationFieldType0;
      Hours hours0 = Hours.ZERO;
      DurationFieldType durationFieldType1 = hours0.getFieldType();
      durationFieldTypeArray0[1] = durationFieldType1;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals("StandardNoYearsNoMonthsNoWeeksNoMinutesNoSecondsNoMillis", periodType0.getName());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      assertEquals("Days", periodType0.getName());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      PeriodType periodType0 = PeriodType.seconds();
      assertNotNull(periodType0);
      
      String string0 = periodType0.toString();
      assertEquals("PeriodType[Seconds]", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      PeriodType periodType0 = PeriodType.millis();
      PeriodType periodType1 = periodType0.withMillisRemoved();
      periodType1.withHoursRemoved();
      assertEquals("MillisNoMillis", periodType1.getName());
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      DurationFieldType[] durationFieldTypeArray0 = new DurationFieldType[1];
      Days days0 = Days.FOUR;
      DurationFieldType durationFieldType0 = days0.getFieldType();
      durationFieldTypeArray0[0] = durationFieldType0;
      PeriodType periodType0 = PeriodType.forFields(durationFieldTypeArray0);
      PeriodType periodType1 = periodType0.withMinutesRemoved();
      assertEquals("Days", periodType1.getName());
  }
}
