/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Feb 24 16:40:53 GMT 2020
 */
package org.apache.commons.math.distribution;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
@EvoSuiteClassExclude
public class PoissonDistributionImpl_ESTest_scaffolding_EvoSuite {
  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 
  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
  } 
  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 
  @Before 
  public void initTestCase(){ 
    setSystemProperties(); 
  } 
  @After 
  public void doneWithTestCase(){ 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
  } 
  public static void setSystemProperties() {
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Etc/UTC"); 
  }
  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PoissonDistributionImpl_ESTest_scaffolding_EvoSuite.class.getClassLoader() ,
      "org.apache.commons.math.random.JDKRandomGenerator",
      "org.apache.commons.math.exception.NumberIsTooSmallException",
      "org.apache.commons.math.MathException",
      "org.apache.commons.math.exception.NonMonotonousSequenceException",
      "org.apache.commons.math.distribution.ContinuousDistribution",
      "org.apache.commons.math.util.FastMath",
      "org.apache.commons.math.util.MathUtils",
      "org.apache.commons.math.distribution.IntegerDistribution",
      "org.apache.commons.math.ConvergenceException",
      "org.apache.commons.math.exception.NotStrictlyPositiveException",
      "org.apache.commons.math.distribution.PoissonDistribution",
      "org.apache.commons.math.analysis.UnivariateRealFunction",
      "org.apache.commons.math.special.Gamma$1",
      "org.apache.commons.math.util.ContinuedFraction",
      "org.apache.commons.math.distribution.Distribution",
      "org.apache.commons.math.random.RandomGenerator",
      "org.apache.commons.math.exception.MathIllegalArgumentException",
      "org.apache.commons.math.distribution.NormalDistribution",
      "org.apache.commons.math.distribution.SaddlePointExpansion",
      "org.apache.commons.math.exception.MathIllegalNumberException",
      "org.apache.commons.math.MathRuntimeException",
      "org.apache.commons.math.MathRuntimeException$1",
      "org.apache.commons.math.MathRuntimeException$2",
      "org.apache.commons.math.MathRuntimeException$3",
      "org.apache.commons.math.MathRuntimeException$4",
      "org.apache.commons.math.MathRuntimeException$5",
      "org.apache.commons.math.MathRuntimeException$6",
      "org.apache.commons.math.distribution.NormalDistributionImpl",
      "org.apache.commons.math.MathRuntimeException$7",
      "org.apache.commons.math.MathRuntimeException$8",
      "org.apache.commons.math.MathRuntimeException$10",
      "org.apache.commons.math.MathRuntimeException$9",
      "org.apache.commons.math.MathRuntimeException$11",
      "org.apache.commons.math.distribution.AbstractIntegerDistribution",
      "org.apache.commons.math.random.RandomData",
      "org.apache.commons.math.distribution.HasDensity",
      "org.apache.commons.math.special.Erf",
      "org.apache.commons.math.random.RandomDataImpl",
      "org.apache.commons.math.exception.NumberIsTooLargeException",
      "org.apache.commons.math.MaxIterationsExceededException",
      "org.apache.commons.math.special.Gamma",
      "org.apache.commons.math.exception.util.Localizable",
      "org.apache.commons.math.FunctionEvaluationException",
      "org.apache.commons.math.distribution.DiscreteDistribution",
      "org.apache.commons.math.distribution.AbstractContinuousDistribution",
      "org.apache.commons.math.exception.util.LocalizedFormats",
      "org.apache.commons.math.util.MathUtils$OrderDirection",
      "org.apache.commons.math.distribution.PoissonDistributionImpl",
      "org.apache.commons.math.distribution.AbstractDistribution",
      "org.apache.commons.math.exception.util.ArgUtils"
    );
  } 
  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PoissonDistributionImpl_ESTest_scaffolding_EvoSuite.class.getClassLoader()); 
    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.math.distribution.AbstractDistribution",
      "org.apache.commons.math.distribution.AbstractIntegerDistribution",
      "org.apache.commons.math.distribution.PoissonDistributionImpl",
      "org.apache.commons.math.exception.util.LocalizedFormats",
      "org.apache.commons.math.util.FastMath",
      "org.apache.commons.math.distribution.SaddlePointExpansion",
      "org.apache.commons.math.special.Gamma",
      "org.apache.commons.math.random.RandomDataImpl",
      "org.apache.commons.math.distribution.AbstractContinuousDistribution",
      "org.apache.commons.math.distribution.NormalDistributionImpl",
      "org.apache.commons.math.special.Erf",
      "org.apache.commons.math.util.ContinuedFraction",
      "org.apache.commons.math.special.Gamma$1",
      "org.apache.commons.math.MathRuntimeException",
      "org.apache.commons.math.MathRuntimeException$4",
      "org.apache.commons.math.random.JDKRandomGenerator",
      "org.apache.commons.math.util.MathUtils",
      "org.apache.commons.math.MathException",
      "org.apache.commons.math.ConvergenceException",
      "org.apache.commons.math.MaxIterationsExceededException",
      "org.apache.commons.math.FunctionEvaluationException",
      "org.apache.commons.math.exception.MathIllegalArgumentException",
      "org.apache.commons.math.exception.MathIllegalNumberException",
      "org.apache.commons.math.exception.NumberIsTooSmallException",
      "org.apache.commons.math.exception.NotStrictlyPositiveException",
      "org.apache.commons.math.exception.util.ArgUtils"
    );
  }
}
