/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 24 16:22:26 GMT 2020
 */

package org.apache.commons.lang3.time;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

public class FastDateParser$TextStrategy_ESTest_EvoSuite extends FastDateParser$TextStrategy_ESTest_scaffolding_EvoSuite {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
